#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies that the application requires to run.

set -e

if ! [ -x "$(command -v dotnet)" ]; then
  echo 'Error: .NET SDK (dotnet command) is not installed or found.  Install via https://dotnet.microsoft.com' >&2
  exit 1
fi


echo 'Everything is ready to go!'