#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  #brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle
  }
fi

# if ci + linux, try installing bats via npm
if [ $CI ] && [ "$(uname -s)" = "Linux" ]; then
  npm install bats
fi

# nuget
echo "==> Installing NuGet dependencies..."
nuget restore src/Compat.sln
