#!/usr/bin/env bash

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

# install dependencies
script/bootstrap

# fiddle PATH for bats
if [ $CI ]; then
  export PATH=$PATH:$(pwd)/node_modules/bats/libexec
fi

# build
xbuild /p:Configuration=Release src/Compat.sln

# test
script/test
