#!/usr/bin/env bash

# script/test: Run test suite for application. Optionally pass in filters for testing
#              e.g. --filter "FullyQualifiedName~AccessTests"

BASE_DIR="$(dirname "$0")/.."

dotnet test $BASE_DIR/src/CompatTests/CompatTests.csproj $@
